from django.contrib import admin
from places.models import Attribute

class AttributeAdmin(admin.ModelAdmin):
    list_display=('osm_id',
                  'name',
                  'lat','lon',
                  'display_name',
                  'address',
                  'county',
                  'suburb',
                  'state_district',
                  'postcode',
                  'country_code',
                  'country',
                  'city',
                  'state',
                  'road',
                  'village',
            
#'admin_level',
'amenity',
'aerialway',
'aeroway',
'area',
'barrier',
'bicycle',
'bridge',
'boundary',
'building',
'capital',
'construction',
'cutting',
'disused',
'ele',
'embankment',
'foot',
'highway',
'historic',
'horse',
'junction',
'landuse',
'layer',
'leisure',
'lock',
'man_made',
'military',
'motorcar',
'natural',
'oneway',
'operator',
'poi',
'power',
'power_source',
'place',
'railway',
'ref',
'religion',
'route',
'service',
'shop',
'sport',
'tourism',
'tunnel',
'waterway',
'width',
'wood')

admin.site.register(Attribute, AttributeAdmin)

