#PLACE TYPE MAX LENGTH
NAME_MAX_LENGTH = 256
SEARCH_RADIUS = 5
PLACE_WT = 10
PLACE_FACTOR_TEXT = 'Recommended'
TIME_WT = 10
TIME_FACTOR_TEXT = 'Timing'
WEATHER_WT = 10
WEATHER_FACTOR_TEXT = 'Weather'
DAY_WT = 10
DAY_FACTOR_TEXT = 'Day'
LOCATON_WT = 10
LOCATON_FACTOR_TEXT = 'Location'
COMBINATION_WT = 10
COMBINATION_FACTOR_TEXT = 'Together'